name: GitHub Container Registry
# added path
on:
  push:
    branches: main
    paths:
      - 'GitHub Container Registry.yml'

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Log in to the GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_CONTAINER_REGISTRY_TOKEN }}
      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/email4prasanth/githubactions_docker/test:latest .

      # Step 4: Push the Docker image to the registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/email4prasanth/githubactions_docker/test:latest
